# Generated by Django 5.1.3 on 2024-12-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_size',
            new_name='size_option',
        ),
    ]
