# Generated by Django 3.2.25 on 2024-11-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DrumKitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bass_drum_size', models.PositiveIntegerField(blank=True, null=True)),
                ('snare_drum_size', models.PositiveIntegerField(blank=True, null=True)),
                ('rack_tom_1_size', models.PositiveIntegerField(blank=True, null=True)),
                ('rack_tom_2_size', models.PositiveIntegerField(blank=True, null=True)),
                ('rack_tom_3_size', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_tom_1_size', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_tom_2_size', models.PositiveIntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('link_to_official_page', models.URLField(blank=True, max_length=1024, null=True)),
                ('sound_recording', models.FileField(blank=True, null=True, upload_to='sound_clips/', validators=[products.models.validate_audio_file])),
                ('add_custom_initial', models.CharField(blank=True, default='', max_length=4)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('drum_kit_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_product', to='products.drumkitdetail')),
            ],
        ),
        migrations.CreateModel(
            name='StandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=254)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stand_detail', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='drumkitdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drum_detail', to='products.product'),
        ),
        migrations.CreateModel(
            name='CymbalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('ride', 'Ride'), ('crash', 'Crash'), ('hi-hat', 'Hi-Hat'), ('splash', 'Splash')], max_length=254)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cymbal_detail', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
