# Generated by Django 3.2.25 on 2024-11-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='drum_kit_detail',
        ),
        migrations.AlterField(
            model_name='drumkitdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drumkit_detail', to='products.product'),
        ),
    ]
