# Generated by Django 5.1.3 on 2024-12-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('7A', '7A'), ('5A', '5A'), ('5B', '5B'), ('2B', '2B')], max_length=2)),
                ('material', models.CharField(choices=[('Maple', 'Maple'), ('Hickory', 'Hickory'), ('Oak', 'Oak'), ('Carbon Fiber', 'Carbon Fiber')], max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stick_detail', to='products.product')),
            ],
        ),
    ]
