# Generated by Django 5.1.3 on 2024-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stickdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickdetail',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stickdetail',
            name='size',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
