# Generated by Django 5.1.3 on 2024-12-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_stickdetail_material_alter_stickdetail_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stickdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_option',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='CymbalDetail',
        ),
        migrations.DeleteModel(
            name='StandDetail',
        ),
        migrations.DeleteModel(
            name='StickDetail',
        ),
    ]
