# Generated by Django 5.1.3 on 2024-12-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_standdetail_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated_on']},
        ),
    ]
